-- Migration: Add Contract System Enums
-- Created: 2025-11-03

-- Extend ContractStatus enum
ALTER TYPE "ContractStatus" ADD VALUE IF NOT EXISTS 'VIEWED';
ALTER TYPE "ContractStatus" ADD VALUE IF NOT EXISTS 'COUNTERSIGNED';
ALTER TYPE "ContractStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "ContractStatus" ADD VALUE IF NOT EXISTS 'TERMINATED';
ALTER TYPE "ContractStatus" ADD VALUE IF NOT EXISTS 'VOIDED';

-- Create new enums
CREATE TYPE "ContractEventType" AS ENUM (
  'CREATED', 'SENT', 'VIEWED', 'SIGNED', 'COUNTERSIGNED',
  'EXPIRED', 'VOIDED', 'LINK_LOCKED', 'REMINDER_SENT',
  'PDF_VIEWED', 'PASSWORD_FAILED', 'OTP_SENT', 'OTP_VERIFIED',
  'SESSION_STARTED', 'SESSION_EXPIRED', 'REISSUED', 'REACTIVATED'
);

CREATE TYPE "DocumentType" AS ENUM (
  'SERVICE_AGREEMENT', 'BOOKING_CONTRACT', 'LICENSE_AGREEMENT',
  'MODEL_RELEASE_ADULT', 'NDA', 'SUBCONTRACTOR_AGREEMENT', 'PRIVACY_CONSENT'
);

CREATE TYPE "EventType" AS ENUM (
  'WEDDING', 'BRAND_EDITORIAL', 'EVENT', 'PORTRAIT'
);

CREATE TYPE "ClauseType" AS ENUM (
  'MANDATORY', 'OPTIONAL', 'CONDITIONAL'
);

CREATE TYPE "ReminderFrequency" AS ENUM (
  'ONCE', 'DAILY', 'EVERY_3_DAYS', 'WEEKLY'
);

CREATE TYPE "InvoiceSchedule" AS ENUM (
  'ON_SIGNING', 'AFTER_EVENT', 'CUSTOM_DAYS'
);
